name: ${project.name}
main: amata1219.parkour.Main
depend: [Votifier]
api-version: 1.13
version: ${project.version}
author: amata1219(Twitter@amata1219)
commands:
  checkarea:
  coin:
  direction:
  parkouredit:
  parkour:
  parkourregion:
  parkoursetting:
  relayout:
  tweet:
  test:
